import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient, Session } from '@supabase/supabase-js';
import { Baby, BookOpen, CheckCircle2, Copy, GraduationCap, Heart, Leaf, Lock, LogOut, Menu, MessageCircle, Mountain, QrCode, Sparkles, Tractor, TreePine, X } from 'lucide-react';
import './styles.css';

type Course = { id?: string; slug: string; title: string; short_desc: string; full_desc?: string; active?: boolean; display_order?: number; cover_url?: string | null };
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
const supabase = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL, SUPABASE_KEY, { auth: { persistSession: true, autoRefreshToken: true } }) : null;
const whatsapp = 'https://wa.me/553299407435';
const pixDefault = 'fundacao@fundacaonn.org';
const nav = (path: string) => { history.pushState(null, '', path); dispatchEvent(new PopStateEvent('popstate')); scrollTo({ top: 0, behavior: 'smooth' }); };
const projects = [{ slug: 'vida-ativa', icon: Heart, title: 'Vida Ativa: Terceira Idade', short: 'Saúde, convivência e conexão com a natureza para a terceira idade.' }, { slug: 'inclusao-e-natureza', icon: Leaf, title: 'Projeto Inclusão e Natureza NN', short: 'Inclusão, cuidado e desenvolvimento para crianças com necessidades especiais.' }, { slug: 'desenvolvimento-infantil', icon: Sparkles, title: 'Projeto Desenvolvimento Infantil NN', short: 'Aventura, aprendizado e formação para o futuro.' }, { slug: 'jovem-do-futuro', icon: GraduationCap, title: 'Projeto Jovem do Futuro NN', short: 'Preparação, direção e oportunidades para a nova geração.' }, { slug: 'empreendedorismo-rural', icon: Tractor, title: 'Projeto Empreendedorismo Rural', short: 'Produção, organização e geração de renda no campo.' }, { slug: 'movimento-e-natureza', icon: Mountain, title: 'Movimento e Natureza', short: 'Movimento, constância e conexão com a natureza.' }, { slug: 'sustentabilidade', icon: TreePine, title: 'Sustentabilidade e Natureza', short: 'Educação ambiental, preservação e produção sustentável.' }];
const fallbackCourses: Course[] = [{ slug: 'jovem-do-futuro', title: 'Jovem do Futuro NN', short_desc: 'Inteligência artificial, educação financeira, empreendedorismo e liderança para jovens.', full_desc: 'Treinamento introdutório da Fundação NN para preparar jovens para o mercado de trabalho e para a vida.' }, { slug: 'empreendedorismo-rural', title: 'Empreendedorismo Rural', short_desc: 'Produção com qualidade, organização coletiva e geração de renda no campo.', full_desc: 'Curso prático para transformar produtores em empreendedores.' }];
function App(){ const [route,setRoute]=useState(location.pathname); useEffect(()=>{const on=()=>setRoute(location.pathname); addEventListener('popstate',on); return()=>removeEventListener('popstate',on)},[]); if(route==='/admin/login') return <AdminLogin/>; if(route.startsWith('/admin')) return <Admin/>; if(route==='/treinamentos') return <Training/>; if(route==='/doacoes') return <Donations/>; const match=route.match(/^\/projetos\/([^/]+)/); if(match) return <Project slug={match[1]}/>; return <Home/>; }
function Header(){ const [open,setOpen]=useState(false); const links=[['/','Início'],['/treinamentos','Treinamentos'],['/doacoes','Doações']]; return <header><button className="brand" onClick={()=>nav('/')}>Fundação NN</button><nav>{links.map(([h,l])=><button key={h} onClick={()=>nav(h)}>{l}</button>)}<a href={whatsapp} target="_blank">WhatsApp</a><button onClick={()=>nav('/admin/login')}>Admin</button></nav><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>{open&&<div className="drawer">{links.map(([h,l])=><button key={h} onClick={()=>{setOpen(false);nav(h)}}>{l}</button>)}</div>}</header> }
function Layout({children}:{children:React.ReactNode}){return <><Header/>{children}<Footer/></>}
function Home(){ return <Layout><main><section className="hero"><div><p className="eyebrow">Caetés · Minas Gerais</p><h1>Brasil, um país de campeões.</h1><p>A Fundação NN desenvolve projetos sociais, ambientais, esportivos e educacionais para transformar pessoas e comunidades.</p><div className="actions"><button className="primary" onClick={()=>nav('/treinamentos')}>Ver treinamentos</button><button className="secondary" onClick={()=>nav('/doacoes')}>Fazer doação</button></div></div><div className="heroMark">NN</div></section><section className="intro"><h2>Projetos que conectam natureza, educação e oportunidade.</h2><p>Atuamos com crianças, jovens, idosos, famílias rurais e iniciativas de sustentabilidade, sempre com frequência, acompanhamento e propósito.</p></section><section className="projects"><h2>Projetos</h2><div className="grid">{projects.map(p=>{const Icon=p.icon;return <article key={p.slug}><Icon/><h3>{p.title}</h3><p>{p.short}</p><button onClick={()=>nav(`/projetos/${p.slug}`)}>Conhecer projeto</button></article>})}</div></section><section className="founder"><div><p className="eyebrow">Fundador</p><h2>Nardel Nascimento</h2><p>Uma trajetória ligada ao esporte, à natureza e ao desenvolvimento humano, transformada em ações concretas para comunidades.</p></div></section><CTA/></main></Layout> }
function Project({slug}:{slug:string}){ const p=projects.find(x=>x.slug===slug)||projects[0]; const Icon=p.icon; return <Layout><main className="page"><Icon className="pageIcon"/><h1>{p.title}</h1><p>{p.short}</p><p>Este projeto conta com atividades frequentes, acompanhamento próximo e ações voltadas para desenvolvimento humano, convivência e autonomia.</p><div className="actions center"><a className="primary" href={`${whatsapp}?text=${encodeURIComponent('Olá, quero participar do projeto '+p.title)}`} target="_blank">Participar</a><button className="secondary dark" onClick={()=>nav('/doacoes')}>Apoiar projeto</button></div></main></Layout> }
function Training(){ const [courses,setCourses]=useState<Course[]>(fallbackCourses); useEffect(()=>{ if(!supabase) return; supabase.from('courses').select('*').eq('active',true).order('display_order').then(({data})=>{ if(data?.length) setCourses(data as Course[]) })},[]); return <Layout><main className="page"><BookOpen className="pageIcon"/><h1>Treinamentos Fundação NN</h1><p>Conteúdos para formação, desenvolvimento e preparação prática.</p><div className="grid training">{courses.map(c=><article key={c.slug}><h3>{c.title}</h3><p>{c.short_desc}</p><details><summary>Acessar treinamento</summary><p>{c.full_desc || c.short_desc}</p><p className="muted">Módulos e aulas podem ser gerenciados pelo painel administrativo quando o Supabase estiver configurado.</p></details></article>)}</div><section className="support"><h2>Apoie os treinamentos</h2><button className="primary" onClick={()=>nav('/doacoes')}>Fazer uma doação</button></section></main></Layout> }
function Donations(){ const [amount,setAmount]=useState(25); const [copied,setCopied]=useState(false); const key=pixDefault; async function copy(){await navigator.clipboard.writeText(key);setCopied(true);setTimeout(()=>setCopied(false),1800)} return <Layout><main className="page donation"><Heart className="pageIcon"/><h1>Apoie a Fundação NN</h1><p>Sua contribuição ajuda a manter projetos sociais, treinamentos e ações de transformação.</p><div className="donationBox"><div><h2>Escolha um valor</h2><div className="amounts">{[10,25,50,100,250].map(v=><button className={v===amount?'active':''} onClick={()=>setAmount(v)} key={v}>R$ {v}</button>)}</div><button className="primary" onClick={copy}>{copied?<CheckCircle2/>:<Copy/>}{copied?'Chave Pix copiada':'Copiar chave Pix'}</button><p className="muted">Chave Pix: {key}</p></div><div className="qr"><QrCode/><span>Use a chave Pix acima no app do banco.</span></div></div></main></Layout> }
function AdminLogin(){ const [email,setEmail]=useState('nardel@fundacaonn.org'); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); async function submit(e:FormEvent){e.preventDefault(); if(!supabase){alert('Configure VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY para ativar o painel.');return} setBusy(true); const {error}=await supabase.auth.signInWithPassword({email,password}); setBusy(false); if(error) alert(error.message); else nav('/admin')} return <main className="login"><form onSubmit={submit}><Lock/><h1>Painel Fundação NN</h1><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" disabled={busy}>{busy?'Entrando...':'Entrar'}</button><button type="button" onClick={()=>nav('/')}>Voltar ao site</button></form></main> }
function Admin(){ const [session,setSession]=useState<Session|null>(null); const [courses,setCourses]=useState<Course[]>(fallbackCourses); const [title,setTitle]=useState(''); useEffect(()=>{ if(!supabase){nav('/admin/login');return} supabase.auth.getSession().then(({data})=>{setSession(data.session); if(!data.session) nav('/admin/login')}); supabase.from('courses').select('*').order('display_order').then(({data})=>{if(data) setCourses(data as Course[])})},[]); async function add(e:FormEvent){e.preventDefault(); if(!supabase||!title)return; const slug=title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''); const {error}=await supabase.from('courses').insert({title,slug,short_desc:'Novo treinamento',active:true,display_order:courses.length+1}); if(error) alert(error.message); else {setTitle(''); const {data}=await supabase.from('courses').select('*').order('display_order'); setCourses((data||[]) as Course[])}} async function logout(){await supabase?.auth.signOut(); nav('/admin/login')} if(!session)return <AdminLogin/>; return <main className="admin"><header><h1>Painel Fundação NN</h1><button onClick={logout}><LogOut/>Sair</button></header><section className="adminGrid"><article><h2>Cursos</h2><p>Total: {courses.length}</p></article><article><h2>Doações</h2><p>Configuração via tabela donation_settings.</p></article><article><h2>Site</h2><p>Conteúdo institucional pronto para edição via Supabase.</p></article></section><form className="editor" onSubmit={add}><h2>Novo curso</h2><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Título do curso"/><button className="primary">Cadastrar</button></form><div className="adminList">{courses.map(c=><article key={c.slug}><h3>{c.title}</h3><p>{c.short_desc}</p></article>)}</div></main> }
function CTA(){return <section className="cta"><h2>Ajude a Fundação NN a ampliar seu impacto.</h2><button className="primary" onClick={()=>nav('/doacoes')}>Fazer uma doação</button></section>}
function Footer(){return <footer><strong>Fundação NN</strong><span>Projetos sociais, natureza, esporte e educação</span><a href={whatsapp} target="_blank">WhatsApp</a></footer>}

createRoot(document.getElementById('root')!).render(<App/>);
