import React from "react";
import { createRoot } from "react-dom/client";
import { BookOpen, CheckCircle2, HeartHandshake, Leaf, PlayCircle, Users } from "lucide-react";
import "./styles.css";

const projects = ["Criança e natureza", "Desenvolvimento infantil", "Jovem futuro", "Movimento e vida ativa", "Sustentabilidade", "Empreendedorismo"];
const pillars = [[HeartHandshake,"Impacto social","Projetos voltados para desenvolvimento humano, comunidade e oportunidade."],[BookOpen,"Formacao","Conteudos, treinamentos e materiais para ampliar conhecimento."],[Users,"Participacao","Caminhos para voluntarios, apoiadores e parceiros se envolverem."],[Leaf,"Raizes Mineiras","Identidade, cultura e iniciativas conectadas ao territorio."]] as const;
function App(){return <main><section className="hero"><nav><strong>Fundacao NN</strong><a href="#participar">Participar</a></nav><div className="heroGrid"><div><p className="eyebrow"><HeartHandshake size={16}/> Institucional · Impacto Social</p><h1>Projetos que fortalecem pessoas, comunidades e futuros possiveis.</h1><p className="lead">Site institucional da Fundacao NN para apresentar pilares, projetos, formacao e oportunidades de participacao.</p><a className="button" href="#projetos">Conhecer projetos</a></div><aside><div className="mark">NN</div><p>Pagamentos, Pix, Stripe e area administrativa serao religados em fase propria, com configuracao real.</p></aside></div></section><section className="section pillars">{pillars.map(([Icon,title,text])=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</section><section className="section projects" id="projetos"><p className="eyebrow">Projetos</p><h2>Frentes para educar, movimentar e transformar.</h2><div>{projects.map(p=><span key={p}>{p}</span>)}</div></section><section className="section cta" id="participar"><PlayCircle/><h2>Participe da proxima etapa</h2><p>A versao GitHub inicial preserva a presenca institucional. Doacoes, cursos e administracao entram depois sem depender da Lovable.</p><ul><li><CheckCircle2/> GitHub Pages preparado</li><li><CheckCircle2/> Sem secrets versionados</li><li><CheckCircle2/> Pagamentos aguardando configuracao real</li></ul></section><footer>Fundacao NN</footer></main>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
